{% set name = "onnx2pytorch" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/onnx2pytorch-{{ version }}.tar.gz
  sha256: b38762a1426944e1273e808a361011358895dbe7cbd87f2d762e0f058e98afa8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pytorch  >=2.0.0
    - onnx >=1.16.0
    - torchvision >=0.15.0

test:
  imports:
    - onnx2pytorch
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ToriML/onnx2pytorch
  summary: Library to transform onnx model to pytorch.
  license: Apache-2.0
  license_file: LICENSE
  description: |
    A library to transform ONNX model to PyTorch. This library enables use of PyTorch backend and all of its great features for manipulation of neural networks.

extra:
  recipe-maintainers:
    - HeavyTony2
