{% set name = "onnx2pytorch" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/onnx2pytorch-{{ version }}.tar.gz
  sha256: 25d4a1061039baf44448ad64cf68388e0e0462f40f827ae68da43691276d1257

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pytorch >=1.4.0 #Currently not avalaible for Windows
    - onnx >=1.6.0
    - torchvision >=0.9.0 #Currently not avalaible for Windows
    - __unix  # [unix]

test:
  imports:
    - onnx2pytorch
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ToriML/onnx2pytorch
  summary: Library to transform onnx model to pytorch.
  license: Apache-2.0
  license_file: LICENSE
  description: |
    A library to transform ONNX model to PyTorch. This library enables use of PyTorch backend and all of its great features for manipulation of neural networks.

extra:
  recipe-maintainers:
    - HeavyTony2
